# Dockerfile.backend
FROM python:3.8-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN apt-get update && apt-get install -y \
    netcat-openbsd gcc postgresql-client libpq-dev && \
    pip install --upgrade pip

COPY requirements ./requirements
COPY requirements.txt .
RUN pip install -r requirements/server.txt

COPY . .

# Comando padrão: será sobrescrito pelo docker-compose
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
